name: Run Scraper

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # ✅ FIX

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Create credentials.json from secret
        run: echo "$GOOGLE_CREDS" > credentials.json
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}


      - name: Run scraper
        env: AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: python scraper.py


      - name: Show log file
        if: always()
        run: cat scraper.log || echo "No scraper.log found"
